[tool.poetry]
name = "dusty"
version = "0.1.0"
description = ""
authors = ["mobo <morgan.bohn@pc-scol.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
openai = "^1.58.1"
tweepy = "^4.14.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
